steps:

# This step builds the container image.
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy
  args: ['functions', 'deploy', 'subscribeSlack', '--gen2', '--trigger-topic', 'cloud-builds', '--runtime', 'nodejs20', '--region', '${_REGION}']
  env: 
    - 'SLACK_WEBHOOK_URL=${_SLACK_WEBHOOK_URL}'
